[package]
name = "harmonia"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = ["rustls"] }
actix-web-lab = "0.17"
rustls = "0.20.2"
rustls-pemfile = "1"
actix-rt = "*"
actix-files = "0.6"
